#version: '3.8'

services:
  backend:
    build: ./backend
    container_name: finance-backend
    env_file:
      - ./backend/.env
    networks:
      - public

  frontend:
    build: ./frontend
    container_name: finance-frontend
    ports:
      - "5173:5173"
    networks:
      - public

networks:
  public:
    external: true
