services:
  haproxy:
    image: haproxy:2.9
    container_name: finance-haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    image: finance-backend:${BACKEND_TAG}
    container_name: finance-backend
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    image: finance-frontend:${FRONTEND_TAG}
    container_name: finance-frontend
    expose:
      - "5173"
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres_finance
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: XwvfD0v2HcypxcK
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5439:5432"

volumes:
  postgres:
