services:
  haproxy:
    image: haproxy:2.9
    container_name: finance-haproxy
    volumes:
      - ../../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ../..//haproxy/ssl/:/usr/local/etc/haproxy/ssl/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    image: f1nanc3/finance-api:${API_TAG}
    container_name: finance-api
    volumes:
      - api:/app/config
      - api:/app/backups
    env_file:
      - .env
    #expose:
    #  - "3001"
    depends_on:
      - postgres

  frontend:
    build: ../../frontend
    image: f1nanc3/finance-ui:${UI_TAG}
    container_name: finance-ui
    depends_on:
      - backend

  postgres:
    image: postgres:14
    container_name: finance-psql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
  api:
